;ADD TWO NUMBERS
;MADE BY DAVID SILVA APANGO
		LIST P=16f84A
		INCLUDE "P16f84A.INC"
		
;;;;;;;;DEFINITIONS

ADDEND1		EQU 0CH
ADDEND2		EQU 0DH
		
RESET
		ORG 00H
		GOTO START

		ORG 08H

;;;;;;;;PIC CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1
		MOVLW	B'00000111'		;FIRST THREE PINS AS INPUTS
		MOVWF	TRISB
		MOVLW	B'00000000'		;PORTB AS OUTPUT
		MOVWF	TRISA
		BCF		STATUS,RP0		;SELECT BANK0
		MOVF	PORTA,0			;MOVE PORTA A W
		MOVWF	ADDEND1			;MOVE W TO ADDEND1
		MOVLW	.5
		MOVWF	ADDEND2
		MOVF	ADDEND1,0
		ADDWF	ADDEND2,0		;ADD, RESULT IN W
 		MOVWF	PORTB			;PRINT IN PORTB
		
		END
