;COUNTS IN BINARY USING LEDS IN PORTB
;MADE BY DAVID SILVA APANGO
        LIST P=16F84A
		INCLUDE "P16F84A.INC"

;;;;;;;;DEFINITIONS

COUNTER		EQU 0CH

RESET
		ORG		00H
		GOTO	START
		
		ORG		04H				;INTERRUPTION
		GOTO	INT

		ORG		08H

;;;;;;;;PIC CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1
		MOVLW	B'00000111'
		MOVWF	OPTION_REG		;MAXIMUM PRESCALER RATE
		MOVLW	B'00000000'
		MOVWF	TRISB			;ALL PORTB AS OUTPUT
		BCF		STATUS,RP0		;SELECT BANK0
		MOVLW	B'10100000'
		MOVWF	INTCON			;ENABLE INTERRUPTIONS; ENABLE T0IF
		MOVLW	B'00000000'
		MOVWF	PORTB			;PORTB STARTS IN ZERO

;;;;;;;;LOAD VARIABLES

		MOVLW	.20
		MOVWF	COUNTER			;LOAD COUNTER (20)
		MOVLW	.59
		MOVWF	TMR0			;LOAD TMR0 (59)

;;;;;;;;PROGRAM START

LOOP	GOTO	LOOP

INT		BCF INTCON,T0IF			;CLEAR INTERRUPTION FLAG
		DECFSZ COUNTER,1		;DECREMENT COUNTER
		GOTO LOAD
		MOVLW .20				;COUNTER IS ZERO
		MOVWF COUNTER			;LOAD COUNTER (20)
		INCF PORTB,1			;INCREMENT PORTA, RESULT IN PORTA
		MOVLW .59
		MOVWF TMR0				;LOAD TMR0 (59)

RET		RETFIE					;END THE INTERRUPTION

		END
