		LIST P=16F877A
		INCLUDE "P16F877A.INC"
		__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _HS_OSC & _LVP_OFF & _BODEN_OFF

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;THIS PROGRAM MANAGES

;-ANALOGIC DIGITAL CONVERTER
;-CONVERSION PRINTING BY LEDS IN PORT D
;-9800 BAUD RATE SERIAL COMUNICATION
;-DATA INPUT FROM 3 ANALOG SENSORS
;-NO TRANSMISSION SUBROUTINES (BLUETOOTH MODULE PROBLEMS)

;;;;;;;;EN PROCESO

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

ANS1		EQU 20H
VALUEL		EQU 21H
VALUEH		EQU 22H
SENSOR0L	EQU 23H
SENSOR0H	EQU 24H
SENSOR1L	EQU 25H
SENSOR1H	EQU 26H
SENSOR2L	EQU 27H
SENSOR2H	EQU 28H
VALVE		EQU 29H				;VALVE CHANGE FLAG

RESET

		ORG		00H
		GOTO	START

		ORG		04H
		GOTO	INT

		ORG		08H

;;;;;;;;INPUTS CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1
		BCF		STATUS,RP1		;SELECT BANK1
		MOVLW	B'00101111'		;RA4 DON'T WORKS FOR THE CONVERTER, DOESN'T HAVE AN!
		MOVWF	TRISA			;INPUTS FOR ANALOGIC SENSORS
		MOVLW	B'00000001'		;INTERRUPTION INPUT FOR RB0 FROM THE KEYBOARD
		MOVWF	TRISB
		MOVLW	B'10000000'		;PIN6 SERIAL OUTPUT (TX)
		MOVWF	TRISC			;PIN7 SERIAL INPUT (RX)
		MOVLW	B'00000000'
		MOVWF	TRISD			;PORT D AS OUTPUT

;;;;;;;;PULL-UP AND TIMER CONFIGURATION

		MOVLW	B'11000000'		;PULL-UP ENABLED
		MOVWF	OPTION_REG		;PRESCALER 1:8 (NO TIMER), INTERRUTION AT HIGH

;;;;;;;;SERIAL PORT CONFIGURATION

		MOVLW		D'129'		;9600 BAUD RATE
		MOVWF		SPBRG		;Fosc/(K*(X+1)) X=SPBRG
		BCF			TXSTA,TX9	;TRANSMISSION AT 8 BITS INSTEAD OF 9
		BCF			TXSTA,SYNC	;ASINCRONOUS MODEFOR USART
		BSF			TXSTA,BRGH	;BAUD RATE HIGH SPEED K=16 (LEAST ERROR AT 9600)
		BSF			TXSTA,TXEN	;TRANSMISSION ENABLED
		BCF			STATUS,RP0	;SELECT BANK0
		BSF			RCSTA,SPEN	;SERIAL PORT ENABLED
		BCF			RCSTA,RX9	;8 BIT RECEPTION
		BSF			RCSTA,CREN	;CONTINUOUS RECEPTION ENABLED

;;;;;;;;INTERRUPTION CONFIGURATIONS

		MOVLW	B'10010000'		;GLOBAL INTERRUPTION ENABLED (GIE)
		MOVWF	INTCON			;RB0 INTERRUPTION ENABLED (INTE)

;;;;;;;;CONVERTER CONFIGURATION

		MOVLW 	B'10000001'		;TOSC*32,CHANNEL 0,CONVERSION DISABLED, CONVERTER TURNED OFF
		MOVWF	ADCON0
		BSF		STATUS,RP0		;SELECT BANK1
		MOVLW	B'10000000'		;ADRESL, TOSC*32, JUSTIFIED TO THE RIGHT, 6 EMPTY BITS IN ADRESH
		MOVWF	ADCON1			;AN7 /A/A/A/A/A/A/A/A/ AN0
		BCF		STATUS,RP0		;SELECT BANK0

;;;;;;;;REGISTER CLEANING

		CLRF	PORTB			;CLEAR PUERTOB
		CLRF	PORTD			;LED RESTART
		CLRF	VALUEL			;CONVERTER REGISTRY RESTART
		CLRF	VALUEH

;;;;;;;;RECEPCION DE DATOS

RCN		BTFSS	PIR1,RCIF		;CHECK RECEPTION FLAG
		GOTO	RCN
		MOVF	RCREG,W			;RECEPTION REGISTRY
		MOVWF	ANS1			;MOVE TO ANS1 CONSTANT
		BCF		PIR1,RCIF		;CLEAR RECEPTION FLAG (IRRELEVANT)

;;;;;;;;CONVERSION STAGE

;;;;;;;;FIRST SENSOR DATA CONVERSION (GAS)

		BCF		ADCON0,3		;CHANNEL0 SELECTION
		BCF		ADCON0,4
		BCF		ADCON0,5
		CALL	CONVERSION
		MOVF	VALUEL,0
		MOVWF	SENSOR0L
		MOVF	VALUEH,0
		MOVWF	SENSOR0H

;;;;;;;;SECOND SENSOR DATA CONVERSION (HUMIDITY)

		BSF		ADCON0,3		;CHANNEL1 SELECTION
		BCF		ADCON0,4
		BCF		ADCON0,5
		CALL	CONVERSION
		MOVF	VALUEL,0
		MOVWF	SENSOR1L
		MOVF	VALUEH,0
		MOVWF	SENSOR1H
						
;;;;;;;;THIRD SENSOR DATA CONVERSION (TEMPERATURE)

		BTFSS	VALVE,0			;CHECK IF GAS MIX CHANGED
		GOTO	JUMP			;NO, DO A MEASUREMENT
		BCF		VALVE,0			;YES, CLEAR FLAG, SEND MARKER
		MOVLW	.82				;40CELSIUS = .82
		MOVWF	SENSOR2L		;CHANGE SIGNAL TO PREDETERMINED VALUES
		CLRF	SENSOR2H		;TO KNOW IF THERE IS A VALVE CHANGE
		GOTO	TRANSMISSION	;SKIP MEASUREMENT AND SEND

JUMP	BCF		VALVE,0
		BCF		ADCON0,3		;CHANNEL2 SELECTION
		BSF		ADCON0,4
		BCF		ADCON0,5
		CALL	CONVERSION
		MOVF	VALUEL,0
		MOVWF	SENSOR2L
		MOVF	VALUEH,0
		MOVWF	SENSOR2H


;;;;;;;;DATA TRANSMISSION

;;;;;;;;FIRST SENSOR

;;;;;;;;FIRST BYTE

		MOVF	SENSOR0H,0		;MOVE CONVERSION TO W
		MOVWF	TXREG			;SEND CONVERSION BY SERIAL PORT
TXN10	BTFSS	PIR1,TXIF		;TRANSMISSION FLAG
		GOTO	TXN10
		BTFSS	PIR1,TXIF		;ASSURE TRANSMISSION FLAG
		GOTO	TXN10
		BCF		PIR1,TXIF		;CLEAR TRANSMISSION FLAG			
;;;;;;;;SECOND BYTE

		MOVF	SENSOR0L,0		;GET MOST SIGNIFICANT BITS
		MOVWF	TXREG			;SEND CONVERSION BY SERIAL PORT
TXN20	BTFSS	PIR1,TXIF		;TRANSMISSION FLAG
		GOTO	TXN20
		BTFSS	PIR1,TXIF		;ASSURE TRANSMISSION FLAG
		GOTO	TXN20
		BCF		PIR1,TXIF		;CLEAR TRANSMISSION FLAG


;;;;;;;;SECOND SENSOR

;;;;;;;;FIRST BYTE

		MOVF	SENSOR1H,0		;MOVE CONVERSION TO W
		MOVWF	TXREG			;SEND CONVERSION BY SERIAL PORT
TXN11	BTFSS	PIR1,TXIF		;TRANSMISSION FLAG
		GOTO	TXN11
		BTFSS	PIR1,TXIF		;ASSURE TRANSMISSION FLAG
		GOTO	TXN11
		BCF		PIR1,TXIF		;CLEAR TRANSMISSION FLAG			
;;;;;;;;SECOND BYTE

		MOVF	SENSOR1L,0		;OBTENER LOS DOS BITS MAS SIGNIFICATICOS
		MOVWF	TXREG			;SEND CONVERSION BY SERIAL PORT
TXN21	BTFSS	PIR1,TXIF		;TRANSMISSION FLAG
		GOTO	TXN21
		BTFSS	PIR1,TXIF		;ASSURE TRANSMISSION FLAG
		GOTO	TXN21
		BCF		PIR1,TXIF		;CLEAR TRANSMISSION FLAG


;;;;;;;;THIRD SENSOR

;;;;;;;;FIRST BYTE

		MOVF	SENSOR2H,0		;MOVE CONVERSION TO W
		MOVWF	TXREG			;SEND CONVERSION BY SERIAL PORT
TXN12	BTFSS	PIR1,TXIF		;TRANSMISSION FLAG
		GOTO	TXN12
		BTFSS	PIR1,TXIF		;ASSURE TRANSMISSION FLAG
		GOTO	TXN12
		BCF		PIR1,TXIF		;BAJAR LA BANDERA DE TRANSMISSION			
;;;;;;;;SECOND BYTE

		MOVF	SENSOR2L,0		;OBTENER LOS DOS BITS MAS SIGNIFICATICOS
		MOVWF	TXREG			;SEND CONVERSION BY SERIAL PORT
TXN22	BTFSS	PIR1,TXIF		;TRANSMISSION FLAG
		GOTO	TXN22
		BTFSS	PIR1,TXIF		;ASSURE TRANSMISSION FLAG
		GOTO	TXN22
		BCF		PIR1,TXIF		;CLEAR TRANSMISSION FLAG
		GOTO	RCN				;GO BACK TO RECEPTION START


;;;;;;;;SUBROUTINES
;;;;;;;;DATA CONVERSION SUBROUTINE

		BSF		ADCON0,ADON		;ENABLE CONVERSION MODULE
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		BSF		ADCON0,GO_DONE	;CONVERSION IN PROGRESS
WAIT	BTFSC	ADCON0,GO_DONE	;WAIT TO THE CONVERSION END
		GOTO	WAIT
		BCF		ADCON0,ADON		;DISABLE CONVERSION MODULE	
		BCF		PIR1,ADIF		;CLEAR CONVERSION FLAG (IRRELEVANT)

;;;;;;;;DAT EXTRACTION

		BSF		STATUS,RP0		;SELECT BANK1
		MOVF	ADRESL,0		;GET 8 LEAST SIGNIFICATIVE BITS
		BCF		STATUS,RP0		;SELECT BANK0
		MOVWF	VALUEL			;SAVE LEAST SIGNIFICATIVE BITS
		MOVWF	PORTD			;PRINT CONVERSION IN LEDS
		MOVF	ADRESH,0		;OBTENER LOS 2 BITS MAS SIGNIFICATIVOS
		MOVWF	VALUEH			;SAVE MOST SIGNIFICATIVE BITS
		RETURN

;;;;;;;;INTERRUPTION ROUTINE

INT		BCF		INTCON,INTF		;CLEAR INTERRUPTION FLAG
		BSF		VALVE,0			;SET GAS VALVE FLAG
;		BTFSC	PORTC,0			;IS THE LED TURN ON
;		GOTO	OFF				;YES, TURN OFF
;		BSF		PORTC,0			;NO, TURN ON
;		GOTO	BACK			;END INTERRUPTION
;OFF	BCF		PORTC,0			;OFF LED

BACK	RETFIE					;END INTERRUPTION
		
		END