;COUNTS IN HEXADECIMAL USING TWO EIGHT SEGMENT DISPLAY
;WHILE YOU CAN TURN ON/OFF TWO LEDS BY PRESSING A BUTTON CONNECTED IN RB0
;MADE BY DAVID SILVA APANGO
		LIST P=16F84A
		INCLUDE "P16F84A.INC"

;;;;;;;;DEFINITIONS

COUNTER		EQU 0CH				;TIMER0 CYCLES
FLAG1		EQU 0DH				;COUNT DOWN, FIRST DISPLAY
DISPLAY1	EQU 0EH				;UP COUNT, FIRST DISPLAY, NEVER GETS TO 0
FLAG2		EQU 0FH				;COUNT DOWN, SECOND DISPLAY
DISPLAY2	EQU 0FH				;UP COUNT, SECOND DISPLAY, NEVER GETS TO 0

RESET
		ORG		00H
		GOTO	START

		ORG		04H
		GOTO	INT
	
		ORG		08H

;;;;;;;;PIC CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1
		MOVLW	B'00000111'
		MOVWF	OPTION_REG		;MAXIMUM PRESCALER RATE
		MOVLW	B'00000000'
		MOVWF	TRISB			;ALL PORTB AS OUTPUT
		MOVLW	B'00000000'
		MOVWF	TRISA			;ALL PORTA AS OUTPUT
		BCF		STATUS,RP0		;SELECT BANK0
		MOVLW	B'10100000'
		MOVWF	INTCON			;ENABLE INTERRUPTIONS, ENABLE T0IE
		MOVLW	B'00000000'
		MOVWF	PORTB			;PORTB STARTS IN ZERO

;;;;;;;;LOAD VARIABLES

LOAD	MOVLW	.16
		MOVWF	FLAG1			;LOAD FLAG (16)
		MOVLW	.0
		MOVWF	DISPLAY1		;LOAD DISPLAY (0)

;;;;;;;;PROGRAM START

COUNT	CALL	DELAY			;DELAY ~1 SECOND
		BTFSS	PORTA,0			;CHANGE DISPLAY
		GOTO	SHOW1			;TURN ON FIRST DISPLAY
		GOTO	SHOW2			;TURN ON SECOND DISPLAY

SHOW1	MOVF	DISPLAY1,0		;MOVE CURRENT NUMBER TO W
		CALL	TABLE			;SELECT DISPLAY NUMBER
		GOTO	DISPLAY

SHOW2	MOVF	DISPLAY2,0		;MOVE CURRENT NUMBER TO W
		CALL	TABLE			;SELECT DISPLAY NUMBER
		GOTO	DISPLAY			

DISPLAY	MOVWF	PORTB			;SHOW CURRENT DISPLAY
		INCF	DISPLAY1,1
		DECFSZ	FLAG1,1			;WAIT FLAG1 RAISING
		GOTO	COUNT			;NEXT NUMBER
		INCF	DISPLAY2,1
		DECFSZ	FLAG2,1			;WAIT FLAG2 RAISING
		GOTO	LOAD			;REPEAT DISPLAY1 FROM ZERO
		MOVLW	.16;			;REPEAT DISPLAY2 FROM ZERO
		MOVWF	FLAG2			;LOAD FLAG2 (16)
		MOVLW	.0
		MOVWF	DISPLAY2		;LOAD DISPLAY (0)
		GOTO	LOAD			;REPEAT DISPLAY1 FROM ZERO TOO


DELAY	MOVLW	.20
		MOVWF	COUNTER			;LOAD COUNTER (20)
TIMER	MOVLW	.59
		MOVWF	TMR0			;LOAD COUNTER (59) ~50MS
SIGNAL	BTFSS	INTCON,T0IF		;IS T0IF SET?
		GOTO	SIGNAL			;NO WAIT
		BCF		INTCON,T0IF		;CLEAR T0IF FLAG
		DECFSZ	COUNTER,1		;DECREMENT COUNTER
		GOTO	TIMER			;LOAD TMR0
		RETURN


TABLE	ADDWF	PCL,F			;MAKE A COMPUTED GOTO
		RETLW	B'00000010'		;0
		RETLW	B'10011110'		;1
		RETLW	B'00100100'		;2
		RETLW	B'00001100'		;3
		RETLW	B'10011000'		;4
		RETLW	B'01001000'		;5
		RETLW	B'01000000'		;6
		RETLW	B'00011110'		;7
		RETLW	B'00000000'		;8
		RETLW	B'00001000'		;9
		RETLW	B'00010000'		;A
		RETLW	B'11000000'		;B
		RETLW	B'01100010'		;C
		RETLW	B'10000100'		;D
		RETLW	B'01100000'		;E
		RETLW	B'01110000'		;F


INT		BCF		INTCON,T0IF		;CLEAR INTERRUPTION FLAG
		BTFSC	PORTA,0			;IS PIN0 TURNED OFF?
		GOTO	OFF				;NO, TURN IT OFF
		BSF		PORTA,0			;YES, TURN IT ON
		BCF		PORTA,1			;TURN OFF PIN1
		GOTO	RET
OFF		BCF		PORTA,0			;TURN OFF PIN0
		BSF		PORTA,1			;TURN ON PIN1


RET		RETFIE


		END