;PULSE COUNTER
;MADE BY DAVID SILVA APANGO
		LIST P=16F877A
		INCLUDE "P16F877A.INC"
		__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _XT_OSC & _LVP_OFF & _BODEN_OFF

;;;;;;;;DEFINITIONS

HTMR1		EQU 20H
COUNTER		EQU 21H

;;;;;;;;PROGRAM START

RESET
		ORG		00H
		GOTO	START

		ORG		04H
		GOTO	INT

		ORG		08H

;;;;;;;;PIC CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1	
		MOVLW	B'00000111'
		MOVWF	OPTION_REG		;ENABLED PULL-UPS, 1:256 PRESCALER
		MOVLW	B'11110000'
		MOVWF	TRISA			;CONFIGURE OUTPUTS FOR COUNTER'S MSB
		MOVLW	B'00000000'
		MOVWF	TRISB			;CONFIGURAR SALIDAS PUERTOB PARA LSB DEL COUNTER
		MOVLW	B'00000001'
		MOVWF	TRISC			;INPUT FOR T1CKI
		MOVLW	B'00000000'
		MOVWF	TRISD			;OUTPUTS FOR COUNTER MIDDLE VALUE
		BSF		PIE1,TMR1IE		;ENABLE TIMER1 INTERRUPTIONS
		BCF		STATUS,RP0		;SELECT BANK0
		MOVLW	B'11000000'		;GLOBAL INTERRUPTION, PERIPHERAL INTERRUPT
		MOVWF	INTCON			;DISABLED INTERRUPTIONS
		MOVLW	B'00000110'		;IRRELEVANT PRESCALER, EXTERNAL CLOCK FROM T1CKI
		MOVWF	T1CON			;DONT SINCRONIZE WITH EXTERNAL CLOCK, STOPPED TMR1

;;;;;;;;PROGRAM START

LOOP	CLRF	HTMR1
		MOVLW	.20				;1 SECOND
		MOVWF	COUNTER			;LOAD COUNTER (20)
		BSF		T1CON,TMR1ON	;TURN ON THE COUNTER
TEMP	MOVLW	.59
		MOVWF	TMR0			;LOAD COUNTER (59)
		BTFSS	INTCON,T0IF		;CHECK FLAG
		GOTO	$-1				;WAIT
		BCF		INTCON,T0IF		;CLEAR FLAG
		DECFSZ	COUNTER,1		;DECREMENT COUNTER
		GOTO	TEMP
		BCF		T1CON,TMR1ON	;TURN OFF TIMER1
		MOVFW	TMR1L
		MOVWF	PORTB			;PRINT PORTB
		MOVFW	TMR1H
		MOVWF	PORTD
		MOVFW	HTMR1
		MOVWF	PORTA
		GOTO	LOOP			;1 SECOND LOOP

;;;;;;;;INTERRUPTION

INT		BCF		PIR1,TMR1IF		;CLEAR FLAG
		INCF	HTMR1,1			;INCREMENT COUNTER
		RETFIE

		END