;MULTIPLIES A STORED NUMBER BY AN INPUT NUMBER BY ADDING SEVERAL TIMES
;MADE BY DAVID SILVA APANGO
		LIST P=16F84A
		INCLUDE "P16f84A.INC"
		
;;;;;;;;DEFINITIONS

MULTIPLICAND	EQU 0CH
MULTIPLIER		EQU 0DH
RESULT 			EQU 0EH
CYCLES 			EQU 0FH


RESET
		ORG 00H
		GOTO START

		ORG 08H

START	BSF		STATUS,RP0		;SELECT BANK1
		MOVLW	B'00000111'		;FIRST THREE PINS AS INPUTS
		MOVWF	TRISA
		MOVLW	B'00000000'		;PORTB AS OUTPUT
		MOVWF	TRISB
		BCF		STATUS,RP0		;SELECT BANK0

;;;;;;;;LOAD VARIABLES

LOOP	MOVLW	B'00000000'     ;START IN ZEROS 
		MOVWF	MULTIPLICAND
		MOVWF	MULTIPLIER
		MOVWF	CYCLES
		MOVF	PORTA,0			;MOVE PORTA TO W
		MOVWF	MULTIPLICAND	;MOVE W TO MULTIPLICAND
		MOVLW	.2
		MOVWF	MULTIPLIER		;MOVE W TO MULTIPLIER
		MOVWF	CYCLES			;MOVE W TO CYCLES
		MOVF	MULTIPLICAND,0	;MOVE MULTIPLICAND TO W
		DECFSZ	CYCLES,1		;SO AS NOT TO MULTIPLY UNNECESSARILY ONCE AGAIN.
		BTFSS	CYCLES,7		;IF PRELOADED NUMBER IS ZERO
		CALL	REPEAT
		CALL	ZERO
		GOTO	LOOP


REPEAT	ADDWF	MULTIPLICAND,0	;ADD CYCLES TO W AND MOVE RESULT IN W
		DECFSZ	CYCLES,1
		GOTO	REPEAT
		MOVWF	RESULT			;MOVE FROM W TO RESULT
 		MOVWF	PORTB			;MOVE FROM W TO PORTB
		BCF		STATUS,Z		
		RETURN

ZERO  	MOVLW	.0
		MOVWF	PORTB
		MOVWF	RESULT
		BCF		STATUS,Z
		GOTO	RET
RET		RETURN

END