;MULTIPLIES A STORED NUMBER BY AN INPUT NUMBER BY ROTATING SEVERAL TIMES
;MADE BY DAVID SILVA APANGO
		LIST P=16F84A
		INCLUDE "P16f84A.INC"

;;;;;;;;DEFINITIONS

MULTIPLICAND	EQU 0CH
MULTIPLIER		EQU 0DH
RESULT 			EQU 0EH
HELPER			EQU 0FH
COUNTER			EQU 10H

RESET
		ORG					00H
		GOTO				START

		ORG					08H

;;;;;;;;PIC CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1
		MOVLW	B'00011111'
		MOVWF	TRISA			;PORTA AS INPUT
		MOVLW	B'00000000'
		MOVWF	TRISB			;PORTB AS OUTPUT
		BCF		STATUS,RP0		;SELECT BANK0

;;;;;;;;LOAD VARIABLES

LOOP	MOVLW	.2				;MULTIPLICAND MUST BE LESS THAN 8 TO AVOID PROBLEMS
		MOVWF	MULTIPLICAND	;LOAD MULTIPLICAND
		MOVWF	HELPER			;LOAD ROTATIONS HELPER
		MOVF	PORTA,0			;(MAX 31)
		MOVWF	MULTIPLIER		;LOAD MULTIPLIER
		MOVLW	.4
		MOVWF	COUNTER			;LOAD COUNTER FOR THREE ROTATIONS (MAX .8)
		CLRF	RESULT			;RESTART RESULT

;;;;;;;;PROGRAM START

MULT	BTFSS	MULTIPLIER,0	;SHALL WE MULTIPLY?
		GOTO	ROTATE			;JUST ROTATE
		MOVFW	HELPER			;ASSURE W'S VALUE 
		ADDWF	RESULT,1
ROTATE	BCF		STATUS,C
		RLF		HELPER,1		;ROTATE HELPER 
        RRF		MULTIPLIER,1	;ROTATE TO CHECK THE BIT
		DECFSZ	COUNTER,1		;HAVE IT FINISHED?
		GOTO	MULT
		MOVF	RESULT,0
		MOVWF	PORTB			;PRINT PORTB
		GOTO	LOOP            ;RETURN

		END