;SELECT A RANDOM NUMBER BY PUSHING A BUTTON
;MADE BY DAVID SILVA APANGO
		LIST P = 16F84A
		INCLUDE "P16F84A.INC"

;;;;;;;;DEFINITIONS

RESULT			EQU 0X0E
PC				EQU 0x02

RESET
		ORG 0
		GOTO	START

		ORG 5

;;;;;;;;PIC CONFIGURATION

START 	BSF		STATUS,RP0		;SELECT BANK1
		MOVLW	B'00000001'
		MOVWF	TRISA			;PIN0 OF PORTA AS INPUT, REST AS OUTPUT
		MOVLW	B'00000000'
		CLRF	TRISB			;PORTB AS OUTPUT
		BCF		STATUS,RP0		;SELECT BANK0
		MOVLW	b'00000001'
		MOVWF	RESULT			;LOAD RESULT

;;;;;;;;PROGRAM START

LOOP	CALL	RANDOM			;SELECT RANDOM NUMBER
		CALL	DEC7SEG			;SELECT DISPLAY NUMBER
		MOVWF	PORTB			;SHOW CURRENT DISPLAY
		GOTO	LOOP


DEC7SEG	ADDWF	PCL,F			;MAKE A COMPUTED GOTO
		RETLW	B'01111001'
		RETLW	B'00000110'
		RETLW	B'01011011'
		RETLW	B'01001111'
		RETLW	B'01100110'
		RETLW	B'01101101'
		RETLW	B'01111101'


RANDOM	BTFSC	PORTA,0			;IS THE BUTTON PRESSED
		GOTO	BACK			;YES, GO BACK
		MOVLW	B'00000110'		;NO
		SUBWF	RESULT,0		;SUBSTRACT 5 TO W
		BTFSC	STATUS,Z		;IS THE RESULT ZERO?
		CLRF	RESULT			;NO, CLEAR RESULT
		INCF	RESULT,1		;YES, INCREMENT RESULT
		GOTO	RANDOM

BACK	MOVF	RESULT,0		;MOVE RESULT TO W
		RETURN
		
		END