;SPI COMMUNICATION (SLAVE)
;MADE BY DAVID SILVA APANGO
		LIST P=16F877A
		INCLUDE "P16F877A.INC"
		__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _HS_OSC & _LVP_OFF & _BODEN_OFF


;;;;;;;;PROGRAMA

RESET
		ORG 00H
		GOTO START

		ORG 08H

;;;;;;;;PIC CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1
		MOVLW	B'00100000'
		MOVWF	TRISA			;PORTA AS OUTPUT
		MOVLW	B'11111111'
		MOVWF	TRISB			;PORTB AS INPUT
		MOVLW	B'00010000'		;PORTC AS SLAVE
		MOVWF	TRISC			;AUTOMATIC SDI,SDO(5)DISABLED,SCK(3)DISABLED,SS(4)ENABLED
		CLRF	OPTION_REG		;PULL-UPS ENABLED,NO TMR0 PRESCALER
		MOVLW	B'11000000'		;INPUT AT OUPUT'S END
		MOVWF	SSPSTAT			;ACTIVE TO INACTIVE TRANSMISSION
		MOVLW	B'00110100'		;NO COLLISIONS, ENABLE SERIAL PORT, HIGH LEVEL INACTIVITY
		MOVWF	SSPCON			;SPI SLAVE MODE, EXTERNAL CLOCK
		BCF		STATUS, RP0		;SELECT BANK0
		MOVLW	B'00110000'
		MOVWF	SSPCON			;1:8 PRESCALER,OSCILLATOR DISABLED
		BSF		STATUS,RP0		;SELECT BANK0
		CLRF	PIE1			;ENABLE SPI INTERRUPTION
		BCF		STATUS,RP0		;SELECT BANK0
		CLRF	PIR1			;CLEAR PERIPHERAL FLAGS
		CLRF	INTCON			;INTERRUPCIONES PERIFERICAS HABILITADAS

;;;;;;;;PROGRAM START

LOOP	MOVFW	PORTB			;MOVE INPUT TO W
		MOVWF	SSPBUF			;SEND FROM BUFFER
		BTFSS	PIR1,SSPIF		;CHECK FLAG
		GOTO	$-1
		BCF		PIR1,SSPIF
		GOTO	LOOP
	
		END