;TIMER0 PROGRAM
;MADE BY DAVID SILVA APANGO
		LIST P=16F84A
		INCLUDE "P16F84A.INC"
		
;;;;;;;;DEFINITIONS

COUNTER 	EQU 0CH

RESET
		ORG		00H
		GOTO	START

		ORG		08H

;;;;;;;;PIC CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1	
		MOVLW	B'00000111'
		MOVWF	OPTION_REG		;ENABLE PULL-UPS, MAXIMUM PRESCALER RATE
		MOVLW	B'00000000'
		MOVWF	TRISB			;PORTB AS OUTPUTS
		BCF		STATUS,RP0		;SELECT BANK0
		CLRF	INTCON			;DISABLE INTERRUPTIONS


BLINK	BSF		PORTB,0			;TURN ON LED
		CALL	DELAY
		BCF		PORTB,0			;TURN OFF LED
		CALL	DELAY
		GOTO	BLINK


DELAY	MOVLW	.20				;1 SEGUNDO
		MOVWF	COUNTER			;LOAD (20)
TEMP	MOVLW	.59
		MOVWF	TMR0			;LOAD (59)
SIGNAL	BTFSS	INTCON,T0IF		;CHECK INTERRUPTION
		GOTO	SIGNAL			;WAIT
		BCF		INTCON,T0IF		;CLEAR FLAG
		DECFSZ	COUNTER,1		;DECREMENT
		GOTO	TEMP			;RETURN
		RETURN

		END

