;BLINK A LED USING TIMER1 
;MADE BY DAVID SILVA APANGO
		LIST P=16F877A
		INCLUDE "P16F877A.INC"
		__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _HS_OSC & _LVP_OFF & _BODEN_OFF

RESET
		ORG		00H
		GOTO	START

		ORG		08H

;;;;;;;;PIC CONFIGURATION

START	BSF		STATUS,RP0		;SELECT BANK1	
		CLRF	OPTION_REG		;PULL-UPS ENABLED,NO TMR0 PRESCALER
		MOVLW	B'00000000'
		MOVWF	TRISB			;PORTB AS OUTPUT
		BCF		STATUS,RP0		;SELECT BANK0
		CLRF	INTCON			;INTERRUPTIONS DISABLED
		MOVLW	B'00110000'		;1:8 PRESCALER,OSCILLATOR DISABLED
		MOVWF	T1CON			;INTERNAL CLOCK,TMR1 STOPPED

;;;;;;;;PROGRAM START

BLINK	BSF		PORTB,0			;TURN ON LED
		CALL	DELAY
		BCF		PORTB,0			;TURN OFF LED
		CALL	DELAY
		GOTO	BLINK


DELAY	CLRF	TMR1L			;COUNT TO THE MAX POSSIBLE
		CLRF	TMR1H			;LOAD ZEROS
		BSF		T1CON,TMR1ON	;TIMER TURNED ON

SIGNAL	BTFSS	PIR1,TMR1IF		;CHECK INTERRUPTION FLAG
		GOTO	SIGNAL          ;WAIT
		BCF		PIR1,TMR1IF		;CLEAR FLAG
		RETURN
				
		END

