		LIST P=16F877A
		INCLUDE "P16F877A.INC"

RESET

		ORG 00H
		GOTO INICIO

		ORG 08H

INICIO	BSF STATUS, RP0		;CAMBIO AL BANCO 1
		MOVLW B'00000001'
		MOVWF TRISA			;PINES DE A COMO ENTRADA
		MOVLW B'00000000'
		MOVWF TRISB			;PINES B COMO SALIDA
		MOVLW B'01100111'
		MOVWF OPTION_REG
		BCF TXSTA,SYNC		;MODO ASINCRONO DE USART
		BSF PIE1,TXIE		;HABILITAR INTERRUPCION POR TRANSMISION
		BSF TXSTA,TX9		;HABILITAR EL NOVENO BIT DE COMUNICACION
		BCF TXSTA,BRGH		;VELOCIDAD BAJA DE TRANSMISION
		MOVLW .155			;VALOR DE LA CONSTANTE X= 155 E=.16%
		MOVWF SPBRG
		BCF STATUS,RP0		;CAMBIO AL BANCO 0
		BSF RCSTA,SPEN		;PUERTOS SERIALES HABILITADOS
		MOVLW B'10000001'	;TOSC*32,CANAL 0,CONVERSION NO ACTIVA,CONVERSOR PERMITIDO
		MOVWF ADCON0
		BSF STATUS, RP0
		MOVLW B'00000000'	;ADRESL, PINES A/A/A/A, 6 BITS VACIOS EN ADRESH
		MOVWF ADCON1
		BCF STATUS,RP0
CICLO	BSF ADCON0,ADON		;ACTIVAR EL MODULO DE CONVERSION
		NOP					
		NOP
		NOP
		NOP
		BSF ADCON0,GO_DONE	;CONVERSION EN CURSO

ESPERA	BTFSC ADCON0,GO_DONE;ESPERAR AL FINAL DE LA CONVERSION
		GOTO ESPERA
		BCF ADCON0,ADON		;DESACTIVAR EL MODULO DE CONVERSION	
		BCF PIR1,ADIF		;BAJAR LA BANDERA DE CONVERSION
		MOVFW ADRESH
		MOVWF PORTB

		GOTO CICLO

		END