		LIST P=16F877A
		INCLUDE "P16F877A.INC"
__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _XT_OSC & _LVP_OFF & _BODEN_OFF

CONTADOR				EQU 0CH
ANS1					EQU					20H								;INICIALIZACION DE VARIABLES
CONSTANTE				EQU					21H
CONSTANTE2				EQU					22H
VALORL					EQU					23H



RESET

						ORG					00H
						GOTO				INICIO

						ORG					08H

;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURACION DE ENTRADAS DEL PIC

INICIO					BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1
						MOVLW				B'00000001'
						MOVWF				TRISA							;PIN DE RA0 COMO ENTRADA PARA CONVERSOR
						MOVLW				B'00000000'
						MOVWF				TRISB							;PINES DE B COMO COMO SALIDAS PARA LED

;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURACIÓN DEL PUERTO SERIAL

						MOVLW				B'10000000'
						MOVWF				TRISC
						MOVLW				D'25'							;9600  BAUDIOS
						;MOVLW				D'12'							;19200 BAUDIOS
						MOVWF				SPBRG							;BAUDIOS Fosc/(K*(X+1)) X=SPBRG
						BCF					TXSTA,TX9						;TRANSMISION A 8 BITS
						BCF					TXSTA,SYNC						;USART MODO ASINCRONO 
						BSF					TXSTA,BRGH						;BAUDIOS RATE HIGH SPEED K=16
						BSF					TXSTA,TXEN						;TRANSMISION HABILITADA

;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURACIÓN DEL CONVERSOR, ETC.

						MOVLW				B'11000111'
						MOVWF				OPTION_REG						;PORTB PULL-UP HABILITADO (SOLO PARA PROGRAMAR)
						BCF					STATUS,RP0
						BCF					STATUS,RP1						;CAMBIO A BANCO 0
						CLRF				INTCON							;INTERRUPCIONES DESHABILITADOS
						BSF					RCSTA,SPEN						;PUERTO SERIAL HABILITADO
						BCF					RCSTA,RX9						;RECEPCION A 8 BITS
						BSF					RCSTA,CREN						;RECIBIMIENTO CONTINUO HABILITADO
						MOVLW 				B'01000001'						;TOSC*32,CANAL 0,CONVERSION NO ACTIVA,CONVERSOR ENCENDIDO
						MOVWF				ADCON0
						BSF					STATUS, RP0						;CAMBIO A BANCO 1
						MOVLW				B'10000001'						;ADRESL, PINES A/A/A/A, 6 BITS VACIOS EN ADRESH
						MOVWF				ADCON1
						BCF					STATUS,RP0						;CAMBIO A BANCO 0

;;;;;;;;;;;;;;;;;;;;;;;;RECEPCION DE DATOS

RCN						BTFSS				PIR1,RCIF						;BANDERA DE RECEPCION ?
						GOTO				RCN
						MOVF				RCREG,W							;REGISTRO DE RECEPCION DE USART
						MOVWF				ANS1							;MOVER A LA CONSTANTE ANS1
						BCF					PIR1,RCIF						;BAJAR LA BANDERA DE RECEPCION

;;;;;;;;;;;;;;;;;;;;;;;;CONVERSION DE DATOS

CICLO					BSF					ADCON0,ADON						;ACTIVAR EL MODULO DE CONVERSION
						NOP					
						NOP
						NOP
						NOP
						BSF					ADCON0,GO_DONE					;CONVERSION EN CURSO
ESPERA					BTFSC				ADCON0,GO_DONE					;ESPERAR AL FINAL DE LA CONVERSION
						GOTO				ESPERA
						BCF					ADCON0,ADON						;DESACTIVAR EL MODULO DE CONVERSION	
						BCF					PIR1,ADIF						;BAJAR LA BANDERA DE CONVERSION

;;;;;;;;;;;;;;;;;;;;;;;;EXTRACCION DE DATOS MENOS SIGNIFICATIVOS

						BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						MOVFW				ADRESL							;OBTENER LOS 8 BITS MENOS SIGNIFICATIVOS
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						MOVWF				VALORL							;MOSTRAR CONVERSION EN LOS LEDS
						MOVWF				PORTB

;;;;;;;;;;;;;;;;;;;;;;;;TRANSMISION DE DATOS

						MOVFW				VALORL							;MOVER CONVERSION A W
						MOVWF				TXREG							;ENVIAR CONVERSIÓN POR EL PUERTO SERIAL
TXN1					BTFSS				PIR1,TXIF						;BANDERA DE TRANSMISION ?
						GOTO				TXN1
						BCF					PIR1,TXIF						;BAJAR LA BANDERA DE TRANSMISION			
					
	
						MOVFW				ADRESH							;OBTENER LOS DOS BITS MAS SIGNIFICATICOS
						MOVWF				TXREG							;ENVIAR CONVERSION POR EL PUERTO SERIAL
TXN2					BTFSS				PIR1,TXIF						;BANDERA DE TRANSMISION ?
						GOTO				TXN2
						BCF					PIR1,TXIF						;BAJAR BANDERA DE TRANSMISION
						GOTO				RCN								;IR A LA PARTE DE RECEPCION


		
						END


