		LIST P=16F877A
		INCLUDE "P16F877A.INC"
		__CONFIG _CP_OFF & _WDT_OFF & _PWRTE_ON & _HS_OSC & _LVP_OFF & _BODEN_OFF

ANS1					EQU					30H								;INICIALIZACION DE VARIABLES
INSTRUCCION				EQU					31H								;REGISTRO DE TRABAJO PARA INSTRUCCIONES A ENVIAR

;;;;;;;;;;;;;;;;;;;;;;;;ROM COMMANDS

SEARCHROM				EQU					32H
READROM					EQU					33H
MATCHROM				EQU					34H
SKIPROM					EQU					35H
ALARM					EQU					36H

;;;;;;;;;;;;;;;;;;;;;;;;FUNCTION COMMANDS

CONVERTT				EQU					37H
WRITESP					EQU					38H
READSP					EQU					39H
COPYSP					EQU					40H
RECALLEE				EQU					41H
READPS					EQU					42H

;;;;;;;;;;;;;;;;;;;;;;;;REGISTROS DE TEMPERATURA

CONTADOR				EQU					47H
CONTBIT					EQU					48H
BYTE					EQU					49H
TLSB					EQU					50H
TMSB					EQU					51H
;CONTADOR				EQU					36H



RESET

						ORG					00H
						GOTO				INICIO

						ORG					08H

;;;;;;;;;;;;;;;;;;;;;;;;ESCRITURA DE INSTRUCCIONES

						MOVLW				B'11110000'						;F0H
						MOVWF				SEARCHROM
						MOVLW				33H								;B'00110011'
						MOVWF				READROM
						MOVLW				55H								;B'01010101'
						MOVWF				MATCHROM
						MOVLW				B'11001100'						;CCH
						MOVWF				SKIPROM
						MOVLW				B'11101100'						;ECH
						MOVWF				ALARM

						MOVLW				B'01000100'						;44H
						MOVWF				CONVERTT
						MOVLW				B'01001110'						;4EH
						MOVWF				WRITESP
						MOVLW				B'10111110'						;BEH
						MOVWF				READSP
						MOVLW				B'01001000'						;48H
						MOVWF				COPYSP
						MOVLW				B'10111000'						;B8H
						MOVWF				RECALLEE
						MOVLW				B'10110100'						;B4H
						MOVWF				READPS



;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURACION DE ENTRADAS DEL PIC

INICIO					BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000000'
						MOVWF				TRISD							;PINES DE B COMO COMO SALIDAS PARA LED

;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURACIÓN DEL PUERTO SERIAL

						MOVLW				B'10000000'
						MOVLW				D'25'							;9600  BAUDIOS
						MOVWF				SPBRG							;BAUDIOS Fosc/(K*(X+1)) X=SPBRG
						BCF					TXSTA,TX9						;TRANSMISION A 8 BITS
						BCF					TXSTA,SYNC						;USART MODO ASINCRONO 
						BSF					TXSTA,BRGH						;BAUDIOS RATE HIGH SPEED K=16
						BSF					TXSTA,TXEN						;TRANSMISION HABILITADA
						MOVLW				B'00000001'						;
						MOVWF				OPTION_REG						;PORTB PULL-UP HABILITADO PREESCALADOR 1:4
						MOVLW				B'10000110'						
						MOVWF				ADCON1
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0
						CLRF				INTCON							;INTERRUPCIONES NO HABILITADAS
						BSF					RCSTA,SPEN						;PUERTO SERIAL HABILITADO
						BCF					RCSTA,RX9						;RECEPCION A 8 BITS
						BSF					RCSTA,CREN						;RECIBIMIENTO CONTINUO HABILITADO
						CLRF				PORTB



;;;;;;;;;;;;;;;;;;;;;;;;RECEPCION DE DATOS

RCN						BTFSS				PIR1,RCIF						;BANDERA DE RECEPCION ?
						GOTO				RCN
						BCF					PIR1,RCIF						;BAJAR LA BANDERA DE RECEPCION
						MOVFW				RCREG							;REGISTRO DE RECEPCION DE USART
						MOVWF				ANS1							;MOVER A LA CONSTANTE ANS1

;;;;;;;;;;;;;;;;;;;;;;;;RESET DEL SENSOR DS18B20

						BCF					INTCON,T0IF						;BAJAR LA BANDERA T0IF
						BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000000'
						MOVWF				TRISA							;PINES DE A COMO SALIDA PARA DS18B20
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0
						BCF					PORTA,0							;ENVIAR SENAL GND AL SENSOR
						MOVLW				.106							;480 us
						MOVWF				TMR0							;COMIENZA EL CONTEO DEL RESET
						BTFSS				INTCON,T0IF						;REVISAR EL DESBORDAMIENTO
						GOTO				$-1
						BCF					INTCON,T0IF						;BAJAR LA BANDERA T0IF
						BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000001'
						MOVWF				TRISA							;PIN 0 DE A COMO ENTRADA PARA DHT22
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0

;;;;;;;;;;;;;;;;;;;;;;;;PULSO DE PRESENCIA

						CALL				PRESENCIA

;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURAR SALIDA

						BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000000'
						MOVWF				TRISA							;PINES DE A COMO SALIDA PARA DS18B20
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0

;;;;;;;;;;;;;;;;;;;;;;;;SKIP ROM COMMAND CCH

						MOVFW				SKIPROM
						CALL				ORDENAR

;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURAR EL SENSOR

						MOVFW				WRITESP
						CALL				ORDENAR
						MOVLW				B'00000000'
						CALL				ORDENAR
						MOVLW				B'00000000'
						CALL				ORDENAR
						MOVFW				B'01111111'
						CALL				ORDENAR

;;;;;;;;;;;;;;;;;;;;;;;;RESET DEL SENSOR DS18B20

						BCF					INTCON,T0IF						;BAJAR LA BANDERA T0IF
						BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000000'
						MOVWF				TRISA							;PINES DE A COMO SALIDA PARA DS18B20
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0
						BCF					PORTA,0							;ENVIAR SENAL GND AL SENSOR
						MOVLW				.106							;480 us
						MOVWF				TMR0							;COMIENZA EL CONTEO DEL RESET
						BTFSS				INTCON,T0IF						;REVISAR EL DESBORDAMIENTO
						GOTO				$-1
						BCF					INTCON,T0IF						;BAJAR LA BANDERA T0IF
						BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000001'
						MOVWF				TRISA							;PIN 0 DE A COMO ENTRADA PARA DHT22
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0

;;;;;;;;;;;;;;;;;;;;;;;;PULSO DE PRESENCIA

						CALL					PRESENCIA

;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURAR SALIDA

						BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000000'
						MOVWF				TRISA							;PINES DE A COMO SALIDA PARA DS18B20
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0

;;;;;;;;;;;;;;;;;;;;;;;;SKIP ROM COMMAND CCH

						MOVFW				SKIPROM
						CALL				ORDENAR

;;;;;;;;;;;;;;;;;;;;;;;;READ SCRATCHPAD COMMAND

						MOVFW				READSP
						CALL				ORDENAR

;;;;;;;;;;;;;;;;;;;;;;;;LECTURA DE REGISTROS

;;;;;;;;;;;;;;;;;;;;;;;;PRIMER REGISTRO (REGISTRO MENOS SIGNIFICATIVO)

						CALL				CAPTURA
						MOVFW				BYTE
						MOVWF				TLSB

;;;;;;;;;;;;;;;;;;;;;;;;SEGUNDO REGISTRO (REGISTRO MAS SIGNIFICATIVO)

						CALL				CAPTURA
						MOVFW				BYTE
						MOVWF				TMSB

;;;;;;;;;;;;;;;;;;;;;;;;TRANSMISION DE DATOS

;;;;;;;;;;;;;;;;;;;;;;;;BYTE MENOS SIGNIFICATIVO


ENVIO					MOVFW				TLSB							;MOVER CONVERSION A W
						MOVWF				PORTD
						MOVWF				TXREG							;ENVIAR CONVERSIÓN POR EL PUERTO SERIAL
TXN1					BTFSS				PIR1,TXIF						;BANDERA DE TRANSMISION ?
						GOTO				TXN1
						BTFSS				PIR1,TXIF						;BANDERA DE TRANSMISION ?
						GOTO				TXN1
						BCF					PIR1,TXIF						;BAJAR LA BANDERA DE TRANSMISION


;;;;;;;;;;;;;;;;;;;;;;;;BYTE MAS SIGNIFICATIVO


						MOVFW				TMSB							;MOVER CONVERSION A W
						MOVWF				TXREG							;ENVIAR CONVERSIÓN POR EL PUERTO SERIAL
TXN2					BTFSS				PIR1,TXIF						;BANDERA DE TRANSMISION ?
						GOTO				TXN2
						BTFSS				PIR1,TXIF						;BANDERA DE TRANSMISION ?
						GOTO				TXN2
						BCF					PIR1,TXIF						;BAJAR LA BANDERA DE TRANSMISION

						GOTO				RCN								;IR A LA PARTE DE RECEPCION DE SENAL DE LA COMPUTADORA.

;;;;;;;;;;;;;;;;;;;;;;;;SUBRUTINAS

;;;;;;;;;;;;;;;;;;;;;;;;PULSO DE PRESENCIA

PRESENCIA				NOP
REVISION60				BTFSC				PORTA,0							;ESPERAR A LA RESPUESTA BAJA DEL SENSOR POR 15-60 us
						GOTO				REVISION60
REVISION240				BTFSS				PORTA,0							;ESPERAR A LA RESPUESTA ALTA DEL SENSOR POR 60-240 us
						GOTO				REVISION240 
						RETURN

;;;;;;;;;;;;;;;;;;;;;;;;ORDENAR INSTRUCCIONES

ORDENAR					MOVWF				INSTRUCCION
						MOVLW				.7		
						MOVWF				CONTADOR						;CARGAR CONTADOR DE BITS
CONDICION				BTFSS				INSTRUCCION,0
						CALL				ENVIARCERO
						CALL				ENVIARUNO
						DECFSZ				CONTADOR,1
						GOTO				CONDICION
						RETURN

;;;;;;;;;;;;;;;;;;;;;;;;ENVIO DE BITS

ENVIARCERO				RRF					INSTRUCCION,1
						BCF					PORTA,0							;ENVIAR SENAL GND AL SENSOR
						MOVLW				.237							;60.8 us
						MOVWF				TMR0							;COMIENZA EL CONTEO
						BTFSS				INTCON,T0IF						;REVISAR EL DESBORDAMIENTO
						GOTO				$-1
						BCF					INTCON,T0IF						;BAJAR LA BANDERA T0IF
						BSF					PORTA,0
						RETURN


ENVIARUNO				RRF					INSTRUCCION,1
						BCF					PORTA,0							;ENVIAR SENAL GND AL SENSOR
						NOP													;1 us DE ESPERA
						NOP
						NOP
						NOP
						NOP
						NOP
						BSF					PORTA,0
						RETURN

;;;;;;;;;;;;;;;;;;;;;;;;CAPTURA DE DATOS

CAPTURA					CLRF				BYTE
						MOVLW				.7
						MOVWF				CONTBIT							;CARGAR CONTADOR DE BITS

NUEVOBIT				BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000000'
						MOVWF				TRISA							;PINES DE A COMO SALIDA PARA DS18B20
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0

						BCF					PORTA,0
						NOP
						NOP
						NOP

;;;;;;;;;;;;;;;;;;;;;;;;CONFIGURAR ENTRADA

						BSF					STATUS,RP0						;CAMBIO AL BANCO 1
						BCF					STATUS,RP1						;CAMBIO AL BANCO 1
						MOVLW				B'00000001'
						MOVWF				TRISA							;PINES DE A COMO ENTRADA PARA DS18B20
						BCF					STATUS,RP0						;CAMBIO AL BANCO 0
						BCF					STATUS,RP1						;CAMBIO AL BANCO 0
						NOP
						NOP
						NOP
						BTFSS				PORTA,0							;QUE BIT ES
						GOTO				CERO
						GOTO				UNO



;;;;;;;;;;;;;;;;;;;;;;;;CAPTURA DE BITS

CERO					RLF					BYTE,1							;CORRER A LA IZQUIERDA ATRAVES DEL CARRY
						BCF					BYTE,0							;PONER BIT EN 0
						CALL				ESPERA60
						DECFSZ				CONTBIT,1						;DECREMENTAR CONTADOR DE BITS
						GOTO				NUEVOBIT						;LA FORMACION DEL REGISTRO NO HA TERMINADO
						RETURN												;TERMINAR SUBRUTINA

UNO						RLF					BYTE,1							;CORRER A LA IZQUIERDA ATRAVES DEL CARRY
						BSF					BYTE,0							;PONER BIT EN 1
						CALL				ESPERA60
						DECFSZ				CONTBIT,1						;DECREMENTAR CONTADOR DE BITS
						GOTO				NUEVOBIT						;LA FORMACION DEL REGISTRO NO HA TERMINADO
						RETURN

ESPERA60				BCF					INTCON,T0IF						;BAJAR LA BANDERA TMR0
						MOVLW				.237
						MOVWF				TMR0							;CONTAR 60.8 us
						BTFSS				INTCON,T0IF
						GOTO				$-1
						RETURN	



						END